export const CHARACTER_CST = {
	DEFAULT_HEX_COLOR: "000000",
	RANDOM_CHARACTER_SATURATION: 0.5,
	RANDOM_CHARACTER_LIGHTNESS: 0.95,
	DEFAULT_ACCESSORY_ID: 1,
	MIN_ACCESSORY_ID: 1,
	MAX_ACCESSORY_ID: 10,
};
