version: "3"
services:
  app:
    env_file:
      - .env
    container_name: app
    ports:
      - "8081:8081"
    depends_on:
      - db
    volumes: 
      - ./question_images:/usr/src/MathEnJeu/dist/server/assets/question_images
      - ./latex_files:/usr/src/MathEnJeu/dist/server/assets/latex_files
      - ./question_html:/usr/src/MathEnJeu/dist/server/assets/question_html

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3307"
    environment:
      - MYSQL_TCP_PORT=3307
    build: ./database
    container_name: db
    cap_add:
      - SYS_NICE
