#source: https://github.com/vuejs/vuejs.org/blob/master/src/v2/cookbook/dockerize-vuejs-app.md
#not the best alternative to run it

FROM node:lts-alpine

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

# run app 
CMD [ "npm", "run", "serve" ]